export const all = db => () => db('comments')
export const create = db => comment => db('comments').insert(comment)
export const remove = db => commentId => db('comments').where('id', commentId).del()
export const update = db => comment => db('comments').where('id', comment.id).update(comment)
export const withId = db => commentId => db('comments').where('id', commentId)
