export const all = db => () => db('posts')
export const create = db => post => db('posts').insert(post)
export const remove = db => postId => db('posts').where('id', postId).del()
export const update = db => post => db('posts').where('id', post.id).update(post)
export const withId = db => postId => db('posts').where('id', postId)
