export const all = db => () => db('users')
export const create = db => userInput => db('users').insert(userInput)
export const remove = db => userId => db('users').where('id', userId).del()
export const update = db => userInput => db('users').update(userInput).where('id', userInput.id)
export const withId = db => userId => db('users').where('id', userId)
export const withName = db => name => db('users').where('name', name)
